[2023-06-19T04:15:27.956+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T04:15:27.957+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T04:15:27.958+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:15:27.958+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T04:15:28.030+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:15:27.960+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T04:15:28.031+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T04:15:28.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.189 seconds
[2023-06-19T04:16:40.806+0000] {processor.py:157} INFO - Started process (PID=128) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T04:16:40.842+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T04:16:40.844+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:16:40.844+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T04:16:40.887+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:16:40.885+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T04:16:40.888+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T04:16:41.002+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.201 seconds
[2023-06-19T04:17:46.918+0000] {processor.py:157} INFO - Started process (PID=157) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T04:17:46.995+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T04:17:46.998+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:17:46.997+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T04:17:47.064+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:17:47.004+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T04:17:47.065+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T04:17:47.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.343 seconds
[2023-06-19T04:18:17.424+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T04:18:17.464+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T04:18:17.465+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:18:17.464+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T04:18:17.467+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:18:17.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T04:18:17.468+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T04:18:17.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.099 seconds
[2023-06-19T04:18:47.861+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T04:18:47.895+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T04:18:47.898+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:18:47.897+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T04:18:47.906+0000] {logging_mixin.py:149} INFO - [2023-06-19T04:18:47.903+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T04:18:47.908+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T04:18:47.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.127 seconds
[2023-06-19T18:42:57.268+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:42:57.336+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:42:57.339+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:42:57.338+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:42:57.510+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:42:57.345+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:42:57.511+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:42:57.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.318 seconds
[2023-06-19T18:44:08.260+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:44:08.324+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:44:08.326+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:44:08.325+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:44:08.370+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:44:08.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:44:08.371+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:44:08.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.261 seconds
[2023-06-19T18:45:13.040+0000] {processor.py:157} INFO - Started process (PID=151) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:45:13.080+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:45:13.081+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:45:13.081+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:45:13.251+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:45:13.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:45:13.252+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:45:13.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.345 seconds
[2023-06-19T18:45:44.093+0000] {processor.py:157} INFO - Started process (PID=218) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:45:44.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:45:44.116+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:45:44.115+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:45:44.118+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:45:44.117+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:45:44.119+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:45:44.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.104 seconds
[2023-06-19T18:46:14.487+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:46:14.490+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:46:14.493+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:46:14.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:46:14.500+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:46:14.497+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:46:14.501+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:46:14.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.092 seconds
[2023-06-19T18:46:44.886+0000] {processor.py:157} INFO - Started process (PID=354) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:46:44.913+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:46:44.914+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:46:44.914+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:46:44.917+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:46:44.916+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:46:44.917+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:46:44.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.087 seconds
[2023-06-19T18:47:15.570+0000] {processor.py:157} INFO - Started process (PID=422) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:47:15.571+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:47:15.572+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:47:15.572+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:47:15.575+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:47:15.574+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:47:15.576+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:47:15.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.074 seconds
[2023-06-19T18:47:45.804+0000] {processor.py:157} INFO - Started process (PID=490) to work on /opt/airflow/dags/load_dag.py
[2023-06-19T18:47:45.805+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-19T18:47:45.806+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:47:45.806+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-19T18:47:45.809+0000] {logging_mixin.py:149} INFO - [2023-06-19T18:47:45.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-19T18:47:45.809+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-19T18:47:45.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.044 seconds
