[2023-06-18T09:50:45.247+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:50:45.248+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:50:45.249+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:50:45.249+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:50:45.416+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:50:45.252+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:50:45.416+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:50:45.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.278 seconds
[2023-06-18T09:51:34.143+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:51:34.250+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:51:34.252+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:34.252+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:51:34.260+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:51:34.257+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:51:34.261+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:51:34.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.265 seconds
[2023-06-18T09:53:08.156+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:53:08.167+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:53:08.168+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:53:08.168+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:53:08.525+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:53:08.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:53:08.526+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:53:08.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.741 seconds
[2023-06-18T09:54:02.102+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:54:02.146+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:54:02.149+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:02.148+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:54:02.158+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:02.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:54:02.160+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:54:02.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.187 seconds
[2023-06-18T09:54:32.913+0000] {processor.py:157} INFO - Started process (PID=288) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:54:32.946+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:54:32.947+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:32.947+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:54:32.950+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:54:32.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:54:32.950+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:54:33.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.119 seconds
[2023-06-18T09:55:04.442+0000] {processor.py:157} INFO - Started process (PID=356) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:55:04.479+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:55:04.480+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:04.479+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:55:04.483+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:04.482+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:55:04.484+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:55:04.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.149 seconds
[2023-06-18T09:55:35.811+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:55:35.849+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:55:35.850+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:35.849+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:55:35.932+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:55:35.851+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:55:35.932+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:55:36.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.268 seconds
[2023-06-18T09:56:06.270+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:56:06.286+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:56:06.287+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:06.287+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:56:06.290+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:06.289+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:56:06.291+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:56:06.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.127 seconds
[2023-06-18T09:56:36.420+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/load_dag.py
[2023-06-18T09:56:36.421+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/load_dag.py for tasks to queue
[2023-06-18T09:56:36.422+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:36.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/load_dag.py
[2023-06-18T09:56:36.424+0000] {logging_mixin.py:149} INFO - [2023-06-18T09:56:36.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/load_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_dag.py", line 6
    from airflow.utils.dates import
                                   ^
SyntaxError: invalid syntax
[2023-06-18T09:56:36.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/load_dag.py
[2023-06-18T09:56:36.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/load_dag.py took 0.126 seconds
